// Dispatch types config
const CHANGE_TITLE = 'CHANGE_TITLE';
const TABLE_RESIZE = 'TABLE_RESIZE';
const CHANGE_TEXT = 'CHANGE_TEXT';
const CHANGE_STYLES = 'CHANGE_STYLES';
const APPLY_STYLES = 'APPLY_STYLES';
const UPDATE_DATE = 'UPDATE_DATE';

export {
    CHANGE_TITLE,
    TABLE_RESIZE,
    CHANGE_TEXT,
    CHANGE_STYLES,
    APPLY_STYLES,
    UPDATE_DATE
};
